export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const SORT_FILTER_ADDED = 'SORT_FILTER_ADDED';
export const ADD_TO_CART = 'ADD_TO_CART';

export const INIT_PRODUCT_DATA = 'INIT_PRODUCT_DATA';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';